# Generated by Django 4.2.3 on 2023-07-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='____', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='exp_sol',
            field=models.TextField(default='____', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
