# Generated by Django 4.2.3 on 2023-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_a', '0002_question_answer_question_exp_sol_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_txt',
            field=models.CharField(max_length=1000),
        ),
    ]
